export const ACTIONS = {
    SET_TURN: 'SET_TURN',
    SET_WON: 'SET_WON',
    SET_GAMEOVER: 'SET_GAMEOVER',
    ADD_FILLED_BOXES: 'ADD_FILLED_BOXES',
    REMOVE_BOX: 'REMOVE_BOX',
    RESTART: 'RESTART',
    SET_RESTART: 'SET_RESTART',
 }
